export interface GameData {
  [category: string]: string[];
}

export const gameData: GameData = {
  Animales: [
    "Perro",
    "Gato",
    "Elefante",
    "León",
    "Tigre",
    "Oso",
    "Lobo",
    "Zorro",
    "Conejo",
    "Caballo",
    "Vaca",
    "Cerdo",
    "Gallina",
    "Pato",
    "Águila",
    "Delfín",
    "Ballena",
    "Tiburón",
    "Serpiente",
    "Cocodrilo",
  ],
  Comida: [
    "Pizza",
    "Sushi",
    "Hamburguesa",
    "Tacos",
    "Pasta",
    "Helado",
    "Chocolate",
    "Pastel",
    "Ensalada",
    "Sopa",
    "Sandwich",
    "Hot Dog",
    "Papas Fritas",
    "Nachos",
    "Burrito",
    "Ramen",
    "Paella",
    "Ceviche",
    "Empanada",
    "Arepa",
  ],
  Lugares: [
    "Playa",
    "Cine",
    "Hospital",
    "Escuela",
    "Restaurante",
    "Aeropuerto",
    "Estación de Tren",
    "Museo",
    "Biblioteca",
    "Gimnasio",
    "Supermercado",
    "Parque",
    "Montaña",
    "Desierto",
    "Bosque",
    "Isla",
    "Ciudad",
    "Pueblo",
    "Castillo",
    "Cueva",
  ],
  Profesiones: [
    "Doctor",
    "Profesor",
    "Chef",
    "Piloto",
    "Bombero",
    "Policía",
    "Ingeniero",
    "Arquitecto",
    "Artista",
    "Músico",
    "Actor",
    "Periodista",
    "Abogado",
    "Veterinario",
    "Astronauta",
    "Científico",
    "Diseñador",
    "Programador",
    "Fotógrafo",
    "Escritor",
  ],
  Deportes: [
    "Fútbol",
    "Básquetbol",
    "Tenis",
    "Natación",
    "Ciclismo",
    "Boxeo",
    "Atletismo",
    "Voleibol",
    "Rugby",
    "Golf",
    "Béisbol",
    "Hockey",
    "Esquí",
    "Surf",
    "Escalada",
    "Yoga",
    "Karate",
    "Patinaje",
    "Gimnasia",
    "Arquería",
  ],
  Tecnología: [
    "Smartphone",
    "Laptop",
    "Tablet",
    "Smartwatch",
    "Auriculares",
    "Cámara",
    "Drone",
    "Robot",
    "Videojuego",
    "Realidad Virtual",
    "Inteligencia Artificial",
    "Blockchain",
    "Criptomoneda",
    "Redes Sociales",
    "Streaming",
    "Podcast",
    "App",
    "Software",
    "Hardware",
    "Internet",
  ],
};

export const categories = Object.keys(gameData);

